defaults:
- models: gat
- datasets: bbbp
- explainers: gnn_gi
device_id: 0
model_name: GCN_3l
record_filename: none
base_dir: ~/GraphCW/
statistics_dir: ~/GraphCW/trainings/
statistics_file: gat_cw_max.json
stratified: false
train_flag: false

concept_whitening: true
concept_dir: ~/GraphCW/molecular_concepts/
concepts: 'qed,logp,tpsa,NOCount,n_heteroatoms'

# ClinTox 'qed,mol_weight,hba,logp,n_heteroatoms'
# TOX21 'hba,hbd,crippenlogp,crippen_mr,nCl'
# BACE 'qed,tpsa,mol_weight,hba,hbd'
# BBBP 'qed,logp,tpsa,NOCount,n_heteroatoms'
# HIV 'logp,hba,hbd,nO,nBondsD2'
